#!/bin/bash

# Mikrus Toolbox - Cloudflare Setup
# Konfiguruje dostęp do API Cloudflare (lokalnie).
# Pozwala na automatyczne dodawanie rekordów DNS.
# Author: Paweł (Lazy Engineer)

set -e

CONFIG_DIR="$HOME/.config/cloudflare"
CONFIG_FILE="$CONFIG_DIR/config"

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  ☁️  Cloudflare DNS Setup                                       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Ten skrypt skonfiguruje dostęp do Cloudflare API."
echo "Będziesz mógł automatycznie dodawać rekordy DNS dla swoich aplikacji."
echo ""

# 1. Sprawdź czy już skonfigurowane
if [ -f "$CONFIG_FILE" ]; then
    echo "⚠️  Znaleziono istniejącą konfigurację: $CONFIG_FILE"
    read -p "Nadpisać? (t/N) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[TtYy]$ ]]; then
        echo "Anulowano."
        exit 0
    fi
fi

# 2. Otwórz przeglądarkę z instrukcjami
echo "📋 Otwieram stronę Cloudflare do utworzenia tokenu..."
echo ""
echo "   W przeglądarce:"
echo "   1. Kliknij 'Create Token'"
echo "   2. Kliknij 'Create Custom Token' (na dole)"
echo "   3. Dodaj uprawnienia:"
echo "      • Zone → DNS → Edit           (wymagane - rekordy DNS)"
echo "      • Zone → Zone Settings → Edit (opcjonalne - SSL, kompresja)"
echo "      • Zone → Cache Rules → Edit   (opcjonalne - cache Next.js)"
echo "   4. W 'Zone Resources' wybierz 'All zones' lub konkretne domeny"
echo "   5. Kliknij 'Continue to summary' → 'Create Token'"
echo "   6. Skopiuj token (pokazuje się tylko raz!)"
echo ""
echo "   💡 Uprawnienia Zone Settings i Cache Rules są potrzebne dla"
echo "      automatycznej optymalizacji (SSL Flexible, Brotli, cache)."
echo ""

# Otwórz przeglądarkę (różne komendy dla różnych systemów)
URL="https://dash.cloudflare.com/profile/api-tokens"
if command -v open &> /dev/null; then
    open "$URL"  # macOS
elif command -v xdg-open &> /dev/null; then
    xdg-open "$URL"  # Linux
elif command -v start &> /dev/null; then
    start "$URL"  # Windows (Git Bash)
else
    echo "   Otwórz ręcznie: $URL"
fi

read -p "Naciśnij Enter gdy skopiujesz token..."

echo ""
read -s -p "🔑 Wklej API Token: " API_TOKEN
echo ""

if [ -z "$API_TOKEN" ]; then
    echo "❌ Token nie może być pusty!"
    exit 1
fi

# 3. Weryfikacja tokenu
echo ""
echo "Weryfikuję token..."

VERIFY_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
    -H "Authorization: Bearer $API_TOKEN" \
    -H "Content-Type: application/json")

if echo "$VERIFY_RESPONSE" | grep -q '"success":true'; then
    echo "✅ Token działa!"
else
    echo "❌ Token nieprawidłowy lub nie ma uprawnień!"
    echo "   Odpowiedź: $VERIFY_RESPONSE"
    exit 1
fi

# 4. Pobierz listę Zone IDs
echo ""
echo "Pobieram listę domen..."

ZONES_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones" \
    -H "Authorization: Bearer $API_TOKEN" \
    -H "Content-Type: application/json")

# Parsuj domeny — wyciągnij pary (id, name) z tablicy result[]
# jq jest preferowane, fallback na grep z parsowaniem per-obiekt
ZONE_PAIRS=""
if command -v jq &>/dev/null; then
    ZONE_PAIRS=$(echo "$ZONES_RESPONSE" | jq -r '.result[] | "\(.name)=\(.id)"' 2>/dev/null)
else
    # Fallback: wyciągnij obiekty z result array i parsuj id+name per obiekt
    # Każdy zone obiekt ma "id" i "name" na początku — bierzemy je parami
    ZONE_PAIRS=$(echo "$ZONES_RESPONSE" \
        | tr '{' '\n' \
        | grep '"name"' \
        | while IFS= read -r obj; do
            local_id=$(echo "$obj" | grep -o '"id":"[^"]*"' | head -1 | sed 's/"id":"//;s/"//')
            local_name=$(echo "$obj" | grep -o '"name":"[^"]*"' | head -1 | sed 's/"name":"//;s/"//')
            # Filtruj: prawdziwa domena musi mieć kropkę, bez spacji
            if [ -n "$local_id" ] && [ -n "$local_name" ] && [[ "$local_name" == *.* ]] && [[ "$local_name" != *" "* ]]; then
                echo "${local_name}=${local_id}"
            fi
        done)
fi

if [ -z "$ZONE_PAIRS" ]; then
    echo "❌ Nie znaleziono żadnych domen!"
    echo "   Upewnij się że token ma dostęp do przynajmniej jednej domeny."
    exit 1
fi

echo ""
echo "Znalezione domeny:"
echo "$ZONE_PAIRS" | cut -d= -f1 | nl
echo ""

# 5. Zapisz konfigurację
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

cat > "$CONFIG_FILE" << EOF
# Cloudflare API Configuration
# Generated by Mikrus Toolbox

API_TOKEN=$API_TOKEN

# Zone mappings (domain=zone_id)
EOF

# Zapisz pary domain=zone_id
echo "$ZONE_PAIRS" >> "$CONFIG_FILE"

chmod 600 "$CONFIG_FILE"

echo ""
echo "✅ Konfiguracja zapisana: $CONFIG_FILE"
echo ""
echo "🚀 Teraz możesz używać:"
echo "   ./local/dns-add.sh subdomena.twojadomena.pl IP_SERWERA"
echo ""
echo "   Przykład:"
echo "   ./local/dns-add.sh status.mojafirma.pl 185.181.10.50"
echo ""
